load("ini/subtiTMMArsyn.RData")
load("ini/methyImputNoBatch450.RData")
load("ini/methyImputNoBatch27.RData")
load("ini/mirTMMARSyn.RData")

shared=lapply(c("LumA","Basal","LumB"),function(x) sapply(list(mirSubti,methySubti,TMMArsyn),function(y) 
	substr(colnames(y[[which(names(y)==x)]]),1,12)))
shared=sapply(1:3,function(x) intersect(intersect(shared[[x]][[1]],shared[[x]][[2]]),shared[[x]][[3]]))
names(shared)=c("LumA","Basal","LumB")
concatenadas=lapply(1:3,function(x) sapply(list(mirSubti,methySubti,TMMArsyn),function(y) 
	y[[which(names(y)==names(shared)[x])]][,substr(colnames(y[[which(names(y)==names(shared)[x])]]),1,12)%in%shared[[x]]]))
sharedHer2=sapply(list(mirSubti,methy27,TMMArsyn),function(y) 
	substr(colnames(y[[which(names(y)=="Her2")]]),1,12))
sharedHer2=intersect(intersect(sharedHer2[[1]],sharedHer2[[2]]),sharedHer2[[3]])
names(concatenadas)=names(shared)
concatenadas$Her2=sapply(list(mirSubti,methy27,TMMArsyn),function(y) 
	y[[which(names(y)=="Her2")]][,substr(colnames(y[[which(names(y)=="Her2")]]),1,12)%in%sharedHer2])
concatenadas=lapply(concatenadas,function(x) sapply(x,function(y) y[,order(substr(colnames(y),1,12))]))
normal=list(mirSubti$normal,methySubti$normal,methy27$normal,TMMArsyn$normal)
save(concatenadas,normal,file="conca/porSubti.RData")
#########################################
concatenadas=lapply(concatenadas,function(x) do.call(rbind,x))
probes=cbind(rownames(concatenadas$LumA),c(rep("miRNA",1588),rep("methy",395808),rep("mRNA",13904)))