load("ini/subtiTMMArsyn.RData")
load("ini/methyImputNoBatch450.RData")
load("ini/methyImputNoBatch27.RData")
load("ini/mirTMMARSyn.RData")

shared=lapply(c("LumA","Basal","LumB"),function(x) sapply(list(mirSubti,methySubti,TMMArsyn),function(y) 
	substr(colnames(y[[which(names(y)==x)]]),1,12)))
shared=sapply(1:3,function(x) intersect(intersect(shared[[x]][[1]],shared[[x]][[2]]),shared[[x]][[3]]))
names(shared)=c("LumA","Basal","LumB")
concatenadas=lapply(1:3,function(x) sapply(list(mirSubti,methySubti,TMMArsyn),function(y) 
	y[[which(names(y)==names(shared)[x])]][,substr(colnames(y[[which(names(y)==names(shared)[x])]]),1,12)%in%shared[[x]]]))
sharedHer2=sapply(list(mirSubti,methy27,TMMArsyn),function(y) 
	substr(colnames(y[[which(names(y)=="Her2")]]),1,12))
sharedHer2=intersect(intersect(sharedHer2[[1]],sharedHer2[[2]]),sharedHer2[[3]])
names(concatenadas)=names(shared)
concatenadas$Her2=sapply(list(mirSubti,methy27,TMMArsyn),function(y) 
	y[[which(names(y)=="Her2")]][,substr(colnames(y[[which(names(y)=="Her2")]]),1,12)%in%sharedHer2])
concatenadas=lapply(concatenadas,function(x) sapply(x,function(y) y[,order(substr(colnames(y),1,12))]))
normal=list(mirSubti$normal,methySubti$normal,methy27$normal,TMMArsyn$normal)
save(concatenadas,normal,file="conca/porSubti.RData")
#########################################
library(pbapply)
library(mixOmics)

concatenadas=lapply(concatenadas,function(x) do.call(rbind,x))
probes=as.data.frame(cbind(rownames(concatenadas$LumA),c(rep("miRNA",1588),rep("methy",395808),rep("mRNA",13904))))
colnames(probes)=c("name","type")

concate.pcas=lapply(concatenadas,function(x) pca(t(x),ncomp=10,center=T,scale=T))
png("subti10compo.png")
> par(mfrow=c(2,2))
> sapply(1:4,function(x) plot(concate.pcas[[x]],main=names(concatenadas)[x]))
> dev.off()

png("Her2dataCorr.png")
plotVar(concate.pcas[[4]],comp=c(1,2),var.names=F,title="Her2",legend=T,
	col=list(rep(c("cornflowerblue","darkmagenta","brown1"),table(probes$type[probes$name%in%rownames(concatenadas1[[4]])]))))
#legend("top",legend=c("methy","miRNA","mRNA"),fill=c("cornflowerblue","green","brown1"))
dev.off()
png("LumAdataCorr.png")
plotVar(concate.pcas[[1]],comp=c(1,2),var.names=F,title="LumA",legend=T,
	col=list(rep(c("cornflowerblue","darkmagenta","brown1"),table(probes$type))))
dev.off()
png("LumBdataCorr.png")
plotVar(concate.pcas[[2]],comp=c(1,2),var.names=F,title="LumB",legend=T,
	col=list(rep(c("cornflowerblue","darkmagenta","brown1"),table(probes$type))))
dev.off()
png("BasaldataCorr.png")
plotVar(concate.pcas[[3]],comp=c(1,2),var.names=F,title="Basal",legend=T,
	col=list(rep(c("cornflowerblue","darkmagenta","brown1"),table(probes$type))))
dev.off()